version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "cd backend && npm install && adonis serve --dev"
    volumes:
         - .:/app
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "cd frontend && yarn start"
    volumes:
         - .:/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000        
  db:
    image: postgres:9.3
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGDATA=/postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_PASSWORD=postgres